language: php
php:
    - '7.0'

sudo: required

services:
    - docker

install:
    - composer install
    - openssl aes-256-cbc -K $encrypted_82f3857e208a_key -iv $encrypted_82f3857e208a_iv -in app/config/parameters_dev_server.yml.enc -out app/config/parameters.yml -d
    - npm install
    - gulp deploy

script: vendor/bin/codecept run -c app/config/codeception.yml

after_success:
    - rm -rf node_modules
    - npm install --only=prod
    - rm -rf vendor
    - composer install --no-dev --optimize-autoloader
    - mkdir build
    - mv .babelrc .gitignore * build
    - ls -Al build/app/config
    - tar -czf mysqlad.tar.gz build
