<?php

namespace AppBundle\Repository;

/**
 * ExplanationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExplanationRepository extends \Doctrine\ORM\EntityRepository
{
}
